# docker-compose.yml
version: '3.9'

services:
  streamlit_original_repo:
    container_name: stable_diffusion_original_repo_streamlit
    # restart: always
    build: 
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./repository:/repository
    ports:
      - "8501:8501"
    stop_signal: SIGKILL
    shm_size: '16gb' 
    runtime: nvidia
    environment:
          - NVIDIA_VISIBLE_DEVICES=all
          - NVIDIA_DRIVER_CAPABILITIES=all
    command: streamlit run --server.port 8501 --server.address 0.0.0.0 /repository/stablediffusion/scripts/demo/sampling.py
